import type { Company } from './types';

// Unicorn startups past and present. Valuations are approximate peak private valuations
// (or IPO-era valuations for graduated companies), in billions of USD.
export const COMPANIES: Company[] = [
  // ---- Present-day private unicorns ----
  { id: 'stripe', name: 'Stripe', domain: 'stripe.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2010, status: 'private', peakValuationB: 95, brandColor: '#635BFF' },
  { id: 'spacex', name: 'SpaceX', domain: 'spacex.com', sector: 'Aerospace', hqCountry: 'USA', hqCity: 'Hawthorne', founded: 2002, status: 'private', peakValuationB: 350, brandColor: '#000000' },
  { id: 'openai', name: 'OpenAI', domain: 'openai.com', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2015, status: 'private', peakValuationB: 300, brandColor: '#10A37F' },
  { id: 'anthropic', name: 'Anthropic', domain: 'anthropic.com', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2021, status: 'private', peakValuationB: 180, brandColor: '#D97757' },
  { id: 'databricks', name: 'Databricks', domain: 'databricks.com', sector: 'Data & Cloud', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2013, status: 'private', peakValuationB: 100, brandColor: '#FF3621' },
  { id: 'canva', name: 'Canva', domain: 'canva.com', sector: 'Design', hqCountry: 'Australia', hqCity: 'Sydney', founded: 2013, status: 'private', peakValuationB: 40, brandColor: '#00C4CC' },
  { id: 'revolut', name: 'Revolut', domain: 'revolut.com', sector: 'Fintech', hqCountry: 'UK', hqCity: 'London', founded: 2015, status: 'private', peakValuationB: 45, brandColor: '#191C1F' },
  { id: 'klarna', name: 'Klarna', domain: 'klarna.com', sector: 'Fintech', hqCountry: 'Sweden', hqCity: 'Stockholm', founded: 2005, status: 'public', peakValuationB: 46, brandColor: '#FFB3C7' },
  { id: 'shein', name: 'Shein', domain: 'shein.com', sector: 'E-commerce', hqCountry: 'Singapore', hqCity: 'Singapore', founded: 2008, status: 'private', peakValuationB: 100, brandColor: '#000000' },
  { id: 'bytedance', name: 'ByteDance', domain: 'bytedance.com', sector: 'Social Media', hqCountry: 'China', hqCity: 'Beijing', founded: 2012, status: 'private', peakValuationB: 300, brandColor: '#325AB4' },
  { id: 'deel', name: 'Deel', domain: 'deel.com', sector: 'HR & Payroll', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2019, status: 'private', peakValuationB: 12, brandColor: '#15357A' },
  { id: 'rippling', name: 'Rippling', domain: 'rippling.com', sector: 'HR & Payroll', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2016, status: 'private', peakValuationB: 16, brandColor: '#FDB71A' },
  { id: 'brex', name: 'Brex', domain: 'brex.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2017, status: 'private', peakValuationB: 12, brandColor: '#F46A35' },
  { id: 'ramp', name: 'Ramp', domain: 'ramp.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'New York', founded: 2019, status: 'private', peakValuationB: 22, brandColor: '#E4F222' },
  { id: 'plaid', name: 'Plaid', domain: 'plaid.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2013, status: 'private', peakValuationB: 13, brandColor: '#111111' },
  { id: 'chime', name: 'Chime', domain: 'chime.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2012, status: 'public', peakValuationB: 25, brandColor: '#1EC677' },
  { id: 'scaleai', name: 'Scale AI', domain: 'scale.com', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2016, status: 'private', peakValuationB: 29, brandColor: '#5B3DF5' },
  { id: 'perplexity', name: 'Perplexity', domain: 'perplexity.ai', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2022, status: 'private', peakValuationB: 20, brandColor: '#20808D' },
  { id: 'mistral', name: 'Mistral AI', domain: 'mistral.ai', sector: 'AI', hqCountry: 'France', hqCity: 'Paris', founded: 2023, status: 'private', peakValuationB: 14, brandColor: '#FF7000' },
  { id: 'xai', name: 'xAI', domain: 'x.ai', sector: 'AI', hqCountry: 'USA', hqCity: 'Palo Alto', founded: 2023, status: 'private', peakValuationB: 200, brandColor: '#000000' },
  { id: 'huggingface', name: 'Hugging Face', domain: 'huggingface.co', sector: 'AI', hqCountry: 'USA', hqCity: 'New York', founded: 2016, status: 'acquired', peakValuationB: 4.5, brandColor: '#FFD21E' },
  { id: 'discord', name: 'Discord', domain: 'discord.com', sector: 'Social Media', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2015, status: 'private', peakValuationB: 15, brandColor: '#5865F2' },
  { id: 'notion', name: 'Notion', domain: 'notion.so', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2013, status: 'private', peakValuationB: 10, brandColor: '#000000' },
  { id: 'epicgames', name: 'Epic Games', domain: 'epicgames.com', sector: 'Gaming', hqCountry: 'USA', hqCity: 'Cary', founded: 1991, status: 'private', peakValuationB: 32, brandColor: '#313131' },
  { id: 'grab', name: 'Grab', domain: 'grab.com', sector: 'Mobility', hqCountry: 'Singapore', hqCity: 'Singapore', founded: 2012, status: 'public', peakValuationB: 40, brandColor: '#00B14F' },
  { id: 'rappi', name: 'Rappi', domain: 'rappi.com', sector: 'Delivery', hqCountry: 'Colombia', hqCity: 'Bogotá', founded: 2015, status: 'private', peakValuationB: 5.25, brandColor: '#FF441F' },
  { id: 'kavak', name: 'Kavak', domain: 'kavak.com', sector: 'Automotive', hqCountry: 'Mexico', hqCity: 'Mexico City', founded: 2016, status: 'private', peakValuationB: 8.7, brandColor: '#2B4EFF' },
  { id: 'getir', name: 'Getir', domain: 'getir.com', sector: 'Delivery', hqCountry: 'Turkey', hqCity: 'Istanbul', founded: 2015, status: 'private', peakValuationB: 11.8, brandColor: '#5D3EBC' },
  { id: 'vercel', name: 'Vercel', domain: 'vercel.com', sector: 'Dev Tools', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2015, status: 'private', peakValuationB: 9.3, brandColor: '#000000' },
  { id: 'nubank', name: 'Nubank', domain: 'nubank.com.br', sector: 'Fintech', hqCountry: 'Brazil', hqCity: 'São Paulo', founded: 2013, status: 'public', peakValuationB: 45, brandColor: '#820AD1' },
  { id: 'gusto', name: 'Gusto', domain: 'gusto.com', sector: 'HR & Payroll', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2011, status: 'private', peakValuationB: 9.5, brandColor: '#F45D48' },
  { id: 'cursor', name: 'Cursor', domain: 'cursor.com', sector: 'Dev Tools', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2022, status: 'private', peakValuationB: 29, brandColor: '#000000' },

  // ---- Graduated unicorns (IPO or acquired) ----
  { id: 'airbnb', name: 'Airbnb', domain: 'airbnb.com', sector: 'Travel', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2008, status: 'public', peakValuationB: 31, brandColor: '#FF5A5F' },
  { id: 'uber', name: 'Uber', domain: 'uber.com', sector: 'Mobility', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2009, status: 'public', peakValuationB: 76, brandColor: '#000000' },
  { id: 'snap', name: 'Snap', domain: 'snap.com', sector: 'Social Media', hqCountry: 'USA', hqCity: 'Santa Monica', founded: 2011, status: 'public', peakValuationB: 24, brandColor: '#FFFC00' },
  { id: 'spotify', name: 'Spotify', domain: 'spotify.com', sector: 'Media', hqCountry: 'Sweden', hqCity: 'Stockholm', founded: 2006, status: 'public', peakValuationB: 26, brandColor: '#1DB954' },
  { id: 'figma', name: 'Figma', domain: 'figma.com', sector: 'Design', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2012, status: 'public', peakValuationB: 20, brandColor: '#F24E1E' },
  { id: 'instacart', name: 'Instacart', domain: 'instacart.com', sector: 'Delivery', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2012, status: 'public', peakValuationB: 39, brandColor: '#43B02A' },
  { id: 'doordash', name: 'DoorDash', domain: 'doordash.com', sector: 'Delivery', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2013, status: 'public', peakValuationB: 16, brandColor: '#FF3008' },
  { id: 'coinbase', name: 'Coinbase', domain: 'coinbase.com', sector: 'Crypto', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2012, status: 'public', peakValuationB: 8, brandColor: '#0052FF' },
  { id: 'robinhood', name: 'Robinhood', domain: 'robinhood.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'Menlo Park', founded: 2013, status: 'public', peakValuationB: 11.7, brandColor: '#00C805' },
  { id: 'duolingo', name: 'Duolingo', domain: 'duolingo.com', sector: 'Education', hqCountry: 'USA', hqCity: 'Pittsburgh', founded: 2011, status: 'public', peakValuationB: 2.4, brandColor: '#58CC02' },
  { id: 'dropbox', name: 'Dropbox', domain: 'dropbox.com', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2007, status: 'public', peakValuationB: 10, brandColor: '#0061FF' },
  { id: 'pinterest', name: 'Pinterest', domain: 'pinterest.com', sector: 'Social Media', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2010, status: 'public', peakValuationB: 12.3, brandColor: '#E60023' },
  { id: 'xiaomi', name: 'Xiaomi', domain: 'mi.com', sector: 'Hardware', hqCountry: 'China', hqCity: 'Beijing', founded: 2010, status: 'public', peakValuationB: 46, brandColor: '#FF6900' },
  { id: 'palantir', name: 'Palantir', domain: 'palantir.com', sector: 'Data & Cloud', hqCountry: 'USA', hqCity: 'Denver', founded: 2003, status: 'public', peakValuationB: 20, brandColor: '#101113' },
  { id: 'zoom', name: 'Zoom', domain: 'zoom.us', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Jose', founded: 2011, status: 'public', peakValuationB: 1, brandColor: '#2D8CFF' },
  { id: 'reddit', name: 'Reddit', domain: 'reddit.com', sector: 'Social Media', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2005, status: 'public', peakValuationB: 10, brandColor: '#FF4500' },
  { id: 'lyft', name: 'Lyft', domain: 'lyft.com', sector: 'Mobility', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2012, status: 'public', peakValuationB: 15.1, brandColor: '#FF00BF' },
  { id: 'peloton', name: 'Peloton', domain: 'onepeloton.com', sector: 'Fitness', hqCountry: 'USA', hqCity: 'New York', founded: 2012, status: 'public', peakValuationB: 4.15, brandColor: '#000000' },
  { id: 'slack', name: 'Slack', domain: 'slack.com', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2009, status: 'acquired', peakValuationB: 27.7, brandColor: '#4A154B' },
  { id: 'github', name: 'GitHub', domain: 'github.com', sector: 'Dev Tools', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2008, status: 'acquired', peakValuationB: 7.5, brandColor: '#24292F' },
  { id: 'wiz', name: 'Wiz', domain: 'wiz.io', sector: 'Cybersecurity', hqCountry: 'USA', hqCity: 'New York', founded: 2020, status: 'acquired', peakValuationB: 32, brandColor: '#1B45F5' },
  { id: 'flipkart', name: 'Flipkart', domain: 'flipkart.com', sector: 'E-commerce', hqCountry: 'India', hqCity: 'Bengaluru', founded: 2007, status: 'acquired', peakValuationB: 21, brandColor: '#2874F0' },
  { id: 'whatsapp', name: 'WhatsApp', domain: 'whatsapp.com', sector: 'Social Media', hqCountry: 'USA', hqCity: 'Mountain View', founded: 2009, status: 'acquired', peakValuationB: 19, brandColor: '#25D366' },
  { id: 'twitch', name: 'Twitch', domain: 'twitch.tv', sector: 'Media', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2011, status: 'acquired', peakValuationB: 1, brandColor: '#9146FF' },
  { id: 'ola', name: 'Ola', domain: 'olacabs.com', sector: 'Mobility', hqCountry: 'India', hqCity: 'Bengaluru', founded: 2010, status: 'private', peakValuationB: 7.3, brandColor: '#000000' },
  { id: 'dji', name: 'DJI', domain: 'dji.com', sector: 'Hardware', hqCountry: 'China', hqCity: 'Shenzhen', founded: 2006, status: 'private', peakValuationB: 15, brandColor: '#000000' },

  // ---- Fallen unicorns ----
  { id: 'theranos', name: 'Theranos', domain: 'theranos.com', sector: 'Healthtech', hqCountry: 'USA', hqCity: 'Palo Alto', founded: 2003, status: 'defunct', peakValuationB: 9, brandColor: '#0B8A4E' },
  { id: 'ftx', name: 'FTX', domain: 'ftx.com', sector: 'Crypto', hqCountry: 'Bahamas', hqCity: 'Nassau', founded: 2019, status: 'defunct', peakValuationB: 32, brandColor: '#02A6C2' },
  { id: 'wework', name: 'WeWork', domain: 'wework.com', sector: 'Real Estate', hqCountry: 'USA', hqCity: 'New York', founded: 2010, status: 'defunct', peakValuationB: 47, brandColor: '#000000' },
  { id: 'quibi', name: 'Quibi', domain: 'quibi.com', sector: 'Media', hqCountry: 'USA', hqCity: 'Los Angeles', founded: 2018, status: 'defunct', peakValuationB: 1.75, brandColor: '#FF5C00' },
  { id: 'jawbone', name: 'Jawbone', domain: 'jawbone.com', sector: 'Hardware', hqCountry: 'USA', hqCity: 'San Francisco', founded: 1999, status: 'defunct', peakValuationB: 3.2, brandColor: '#000000' },
  { id: 'zume', name: 'Zume', domain: 'zume.com', sector: 'Robotics', hqCountry: 'USA', hqCity: 'Mountain View', founded: 2015, status: 'defunct', peakValuationB: 2.25, brandColor: '#E4002B' },
  { id: 'convoy', name: 'Convoy', domain: 'convoy.com', sector: 'Logistics', hqCountry: 'USA', hqCity: 'Seattle', founded: 2015, status: 'defunct', peakValuationB: 3.8, brandColor: '#0A2540' },
  { id: 'oliveai', name: 'Olive AI', domain: 'oliveai.com', sector: 'Healthtech', hqCountry: 'USA', hqCity: 'Columbus', founded: 2012, status: 'defunct', peakValuationB: 4, brandColor: '#6B4EFF' },
  { id: 'katerra', name: 'Katerra', domain: 'katerra.com', sector: 'Construction', hqCountry: 'USA', hqCity: 'Menlo Park', founded: 2015, status: 'defunct', peakValuationB: 4, brandColor: '#1E3A5F' },
  { id: 'hopin', name: 'Hopin', domain: 'hopin.com', sector: 'Events', hqCountry: 'UK', hqCity: 'London', founded: 2019, status: 'defunct', peakValuationB: 7.75, brandColor: '#2D3DFF' },
  { id: 'byjus', name: "Byju's", domain: 'byjus.com', sector: 'Education', hqCountry: 'India', hqCity: 'Bengaluru', founded: 2011, status: 'defunct', peakValuationB: 22, brandColor: '#813588' },
  { id: 'cazoo', name: 'Cazoo', domain: 'cazoo.co.uk', sector: 'Automotive', hqCountry: 'UK', hqCity: 'London', founded: 2018, status: 'defunct', peakValuationB: 7, brandColor: '#00B4A0' },
  { id: 'bird', name: 'Bird', domain: 'bird.co', sector: 'Mobility', hqCountry: 'USA', hqCity: 'Miami', founded: 2017, status: 'defunct', peakValuationB: 2.85, brandColor: '#000000' },
  { id: 'fab', name: 'Fab.com', domain: 'fab.com', sector: 'E-commerce', hqCountry: 'USA', hqCity: 'New York', founded: 2010, status: 'defunct', peakValuationB: 1, brandColor: '#E0245E' },
  { id: 'zenefits', name: 'Zenefits', domain: 'zenefits.com', sector: 'HR & Payroll', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2013, status: 'acquired', peakValuationB: 4.5, brandColor: '#FF5745' },
  { id: 'gorillas', name: 'Gorillas', domain: 'gorillas.io', sector: 'Delivery', hqCountry: 'Germany', hqCity: 'Berlin', founded: 2020, status: 'acquired', peakValuationB: 3, brandColor: '#000000' },
  { id: 'vroom', name: 'Vroom', domain: 'vroom.com', sector: 'Automotive', hqCountry: 'USA', hqCity: 'New York', founded: 2013, status: 'defunct', peakValuationB: 1.5, brandColor: '#E7131A' },
  // ---- More present-day private unicorns ----
  { id: 'anduril', name: 'Anduril', domain: 'anduril.com', sector: 'Defense', hqCountry: 'USA', hqCity: 'Costa Mesa', founded: 2017, status: 'private', peakValuationB: 30.5, brandColor: '#000000' },
  { id: 'airtable', name: 'Airtable', domain: 'airtable.com', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2012, status: 'private', peakValuationB: 11, brandColor: '#FCB400' },
  { id: 'miro', name: 'Miro', domain: 'miro.com', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2011, status: 'private', peakValuationB: 17.5, brandColor: '#FFD02F' },
  { id: 'grammarly', name: 'Grammarly', domain: 'grammarly.com', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2009, status: 'private', peakValuationB: 13, brandColor: '#15C39A' },
  { id: 'supabase', name: 'Supabase', domain: 'supabase.com', sector: 'Dev Tools', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2020, status: 'private', peakValuationB: 5, brandColor: '#3ECF8E' },
  { id: 'linear', name: 'Linear', domain: 'linear.app', sector: 'Productivity', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2019, status: 'private', peakValuationB: 1.25, brandColor: '#5E6AD2' },
  { id: 'lovable', name: 'Lovable', domain: 'lovable.dev', sector: 'AI', hqCountry: 'Sweden', hqCity: 'Stockholm', founded: 2023, status: 'private', peakValuationB: 1.8, brandColor: '#FF6B6B' },
  { id: 'elevenlabs', name: 'ElevenLabs', domain: 'elevenlabs.io', sector: 'AI', hqCountry: 'USA', hqCity: 'New York', founded: 2022, status: 'private', peakValuationB: 6.6, brandColor: '#000000' },
  { id: 'runway', name: 'Runway', domain: 'runwayml.com', sector: 'AI', hqCountry: 'USA', hqCity: 'New York', founded: 2018, status: 'private', peakValuationB: 3, brandColor: '#000000' },
  { id: 'groq', name: 'Groq', domain: 'groq.com', sector: 'AI', hqCountry: 'USA', hqCity: 'Mountain View', founded: 2016, status: 'private', peakValuationB: 6.9, brandColor: '#F55036' },
  { id: 'cerebras', name: 'Cerebras', domain: 'cerebras.ai', sector: 'AI', hqCountry: 'USA', hqCity: 'Sunnyvale', founded: 2015, status: 'private', peakValuationB: 8.1, brandColor: '#F15A29' },
  { id: 'sierra', name: 'Sierra', domain: 'sierra.ai', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2023, status: 'private', peakValuationB: 10, brandColor: '#1B1B1B' },
  { id: 'harvey', name: 'Harvey', domain: 'harvey.ai', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2022, status: 'private', peakValuationB: 5, brandColor: '#000000' },
  { id: 'glean', name: 'Glean', domain: 'glean.com', sector: 'AI', hqCountry: 'USA', hqCity: 'Palo Alto', founded: 2019, status: 'private', peakValuationB: 7.2, brandColor: '#343CED' },
  { id: 'cohere', name: 'Cohere', domain: 'cohere.com', sector: 'AI', hqCountry: 'Canada', hqCity: 'Toronto', founded: 2019, status: 'private', peakValuationB: 6.8, brandColor: '#39594D' },
  { id: 'ssi', name: 'SSI', domain: 'ssi.inc', sector: 'AI', hqCountry: 'USA', hqCity: 'Palo Alto', founded: 2024, status: 'private', peakValuationB: 32, brandColor: '#000000' },
  { id: 'thinkingmachines', name: 'Thinking Machines', domain: 'thinkingmachines.ai', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2025, status: 'private', peakValuationB: 12, brandColor: '#000000' },
  { id: 'zepto', name: 'Zepto', domain: 'zeptonow.com', sector: 'Delivery', hqCountry: 'India', hqCity: 'Mumbai', founded: 2021, status: 'private', peakValuationB: 5, brandColor: '#3C0A7B' },
  { id: 'razorpay', name: 'Razorpay', domain: 'razorpay.com', sector: 'Fintech', hqCountry: 'India', hqCity: 'Bengaluru', founded: 2014, status: 'private', peakValuationB: 7.5, brandColor: '#0C2451' },
  { id: 'phonepe', name: 'PhonePe', domain: 'phonepe.com', sector: 'Fintech', hqCountry: 'India', hqCity: 'Bengaluru', founded: 2015, status: 'private', peakValuationB: 12, brandColor: '#5F259F' },
  { id: 'oyo', name: 'OYO', domain: 'oyorooms.com', sector: 'Travel', hqCountry: 'India', hqCity: 'Gurugram', founded: 2012, status: 'private', peakValuationB: 10, brandColor: '#EE2E24' },
  { id: 'dream11', name: 'Dream11', domain: 'dream11.com', sector: 'Gaming', hqCountry: 'India', hqCity: 'Mumbai', founded: 2008, status: 'private', peakValuationB: 8, brandColor: '#D51E3C' },
  { id: 'monzo', name: 'Monzo', domain: 'monzo.com', sector: 'Fintech', hqCountry: 'UK', hqCity: 'London', founded: 2015, status: 'private', peakValuationB: 5.9, brandColor: '#FF4D56' },
  { id: 'checkout', name: 'Checkout', domain: 'checkout.com', sector: 'Fintech', hqCountry: 'UK', hqCity: 'London', founded: 2012, status: 'private', peakValuationB: 40, brandColor: '#0B0B0B' },
  { id: 'n26', name: 'N26', domain: 'n26.com', sector: 'Fintech', hqCountry: 'Germany', hqCity: 'Berlin', founded: 2013, status: 'private', peakValuationB: 9, brandColor: '#36A18B' },
  { id: 'traderepublic', name: 'Trade Republic', domain: 'traderepublic.com', sector: 'Fintech', hqCountry: 'Germany', hqCity: 'Berlin', founded: 2015, status: 'private', peakValuationB: 5.3, brandColor: '#000000' },
  { id: 'celonis', name: 'Celonis', domain: 'celonis.com', sector: 'Data & Cloud', hqCountry: 'Germany', hqCity: 'Munich', founded: 2011, status: 'private', peakValuationB: 13, brandColor: '#1A0F91' },
  { id: 'helsing', name: 'Helsing', domain: 'helsing.ai', sector: 'Defense', hqCountry: 'Germany', hqCity: 'Munich', founded: 2021, status: 'private', peakValuationB: 12, brandColor: '#000000' },
  { id: 'bolt', name: 'Bolt', domain: 'bolt.eu', sector: 'Mobility', hqCountry: 'Estonia', hqCity: 'Tallinn', founded: 2013, status: 'private', peakValuationB: 8.4, brandColor: '#34D186' },
  { id: 'vinted', name: 'Vinted', domain: 'vinted.com', sector: 'E-commerce', hqCountry: 'Lithuania', hqCity: 'Vilnius', founded: 2008, status: 'private', peakValuationB: 5, brandColor: '#09B1BA' },
  { id: 'oura', name: 'Oura', domain: 'ouraring.com', sector: 'Hardware', hqCountry: 'Finland', hqCity: 'Oulu', founded: 2013, status: 'private', peakValuationB: 11, brandColor: '#000000' },
  { id: 'kraken', name: 'Kraken', domain: 'kraken.com', sector: 'Crypto', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2011, status: 'private', peakValuationB: 15, brandColor: '#5741D9' },
  { id: 'alchemy', name: 'Alchemy', domain: 'alchemy.com', sector: 'Crypto', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2017, status: 'private', peakValuationB: 10.2, brandColor: '#363FF9' },
  { id: 'mercury', name: 'Mercury', domain: 'mercury.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2017, status: 'private', peakValuationB: 3.5, brandColor: '#5266EB' },
  { id: 'carta', name: 'Carta', domain: 'carta.com', sector: 'Fintech', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2012, status: 'private', peakValuationB: 7.4, brandColor: '#000000' },
  { id: 'airwallex', name: 'Airwallex', domain: 'airwallex.com', sector: 'Fintech', hqCountry: 'Singapore', hqCity: 'Singapore', founded: 2015, status: 'private', peakValuationB: 6.2, brandColor: '#FF4F00' },
  { id: 'whatnot', name: 'Whatnot', domain: 'whatnot.com', sector: 'E-commerce', hqCountry: 'USA', hqCity: 'Los Angeles', founded: 2019, status: 'private', peakValuationB: 11.5, brandColor: '#FFDF00' },
  { id: 'faire', name: 'Faire', domain: 'faire.com', sector: 'E-commerce', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2017, status: 'private', peakValuationB: 12.6, brandColor: '#000000' },
  { id: 'gopuff', name: 'Gopuff', domain: 'gopuff.com', sector: 'Delivery', hqCountry: 'USA', hqCity: 'Philadelphia', founded: 2013, status: 'private', peakValuationB: 15, brandColor: '#00A6FF' },
  { id: 'zipline', name: 'Zipline', domain: 'flyzipline.com', sector: 'Logistics', hqCountry: 'USA', hqCity: 'South San Francisco', founded: 2014, status: 'private', peakValuationB: 4.2, brandColor: '#000000' },
  { id: 'nuro', name: 'Nuro', domain: 'nuro.ai', sector: 'Robotics', hqCountry: 'USA', hqCity: 'Mountain View', founded: 2016, status: 'private', peakValuationB: 8.6, brandColor: '#000000' },
  { id: 'neuralink', name: 'Neuralink', domain: 'neuralink.com', sector: 'Healthtech', hqCountry: 'USA', hqCity: 'Austin', founded: 2016, status: 'private', peakValuationB: 9, brandColor: '#000000' },
  { id: 'colossal', name: 'Colossal', domain: 'colossal.com', sector: 'Biotech', hqCountry: 'USA', hqCity: 'Dallas', founded: 2021, status: 'private', peakValuationB: 10.2, brandColor: '#000000' },
  { id: 'shieldai', name: 'Shield AI', domain: 'shield.ai', sector: 'Defense', hqCountry: 'USA', hqCity: 'San Diego', founded: 2015, status: 'private', peakValuationB: 5.3, brandColor: '#000000' },
  { id: 'gong', name: 'Gong', domain: 'gong.io', sector: 'AI', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2015, status: 'private', peakValuationB: 7.25, brandColor: '#8039DF' },
  { id: 'calendly', name: 'Calendly', domain: 'calendly.com', sector: 'Productivity', hqCountry: 'USA', hqCity: 'Atlanta', founded: 2013, status: 'private', peakValuationB: 3, brandColor: '#006BFF' },
  { id: 'strava', name: 'Strava', domain: 'strava.com', sector: 'Fitness', hqCountry: 'USA', hqCity: 'San Francisco', founded: 2009, status: 'private', peakValuationB: 2.2, brandColor: '#FC4C02' },
  { id: 'liquiddeath', name: 'Liquid Death', domain: 'liquiddeath.com', sector: 'Consumer', hqCountry: 'USA', hqCity: 'Los Angeles', founded: 2017, status: 'private', peakValuationB: 1.4, brandColor: '#000000' },
];

/**
 * The curated deck: private unicorns that get mainstream coverage. Everything else in
 * COMPANIES stays available but is never dealt. Edit this list to tune the game.
 */
export const CURATED_IDS = [
  // AI
  'openai', 'anthropic', 'xai', 'mistral', 'perplexity', 'scaleai', 'cursor', 'elevenlabs',
  'runway', 'groq', 'cerebras', 'ssi', 'thinkingmachines', 'cohere', 'harvey', 'sierra', 'lovable',
  // Fintech
  'stripe', 'revolut', 'brex', 'ramp', 'plaid', 'mercury', 'kraken',
  // Productivity and developer tools
  'notion', 'canva', 'vercel', 'supabase', 'linear', 'miro', 'grammarly',
  // Everything else
  'spacex', 'discord', 'epicgames', 'bytedance', 'neuralink', 'anduril', 'databricks',
  'deel', 'rippling', 'gusto', 'whatnot', 'zipline', 'oura', 'dji', 'strava',
];

const curated = new Set(CURATED_IDS);
export const DECK: Company[] = COMPANIES.filter((c) => c.status === 'private' && curated.has(c.id));

export const COMPANY_BY_ID: Record<string, Company> = Object.fromEntries(
  COMPANIES.map((c) => [c.id, c]),
);
